spring.application.name=centroSportivo

spring.datasource.url=jdbc:postgresql://localhost:5432/sportivo
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false