spring.application.name=centroSportivo

spring.datasource.url=jdbc:postgresql://localhost:5432/sportivo
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# 1. Configurazione Server
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
# 2. Le tue credenziali
#spring.mail.username=${EMAIL}
# 3 pass
#spring.mail.password=${PASSWORD}
# 3. Protocollo di sicurezza
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081
jwt.secret-key=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000